export function getTypeColor(type: string) {
  if (type === 'bug') return 'bg-lime-600'
  if (type === 'grass') return 'bg-green-600'
  if (type === 'poison') return 'bg-purple-600'
  if (type === 'fairy') return 'bg-pink-400'
  if (type === 'fire') return 'bg-orange-600'
  if (type === 'flying') return 'bg-indigo-400'
  if (type === 'normal') return 'bg-zinc-400'
  if (type === 'water') return 'bg-sky-600'
  if (type === 'dragon') return 'bg-blue-600'
  if (type === 'psychic') return 'bg-rose-400'
  if (type === 'rock') return 'bg-stone-500'
  if (type === 'ground') return 'bg-amber-500'
  if (type === 'fighting') return 'bg-rose-700'
  if (type === 'ghost') return 'bg-indigo-700'
  if (type === 'ice') return 'bg-teal-300 text-zinc-500'
  if (type === 'steel') return 'bg-slate-500'
  if (type === 'dark') return 'bg-slate-700'
  if (type === 'electric') return 'bg-yellow-400 text-zinc-500'
}
